#!/bin/bash

cd /usr/src/crac

curl http://www.crac.org.cn/?page_id=1682 2>/dev/null | grep attachment | sed -e "s/.*href=\"//" | cut -f1 -d\" | head -5 > n
cat n
for u in `cat n`;do
echo ============
echo download $u
curl $u 2>/dev/null | grep csv | grep title | sed -e "s/.*href=\"//" | cut -f1 -d\" > n1
cat n1
wget -O t1 `cat n1`
php insertintodb.php t1
done

rm -f n n1 t1

